sudo: required
dist: trusty

language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq uthash-dev luajit

before-script:
  - test $CC = clang && sudo rm /usr/bin/ld && sudo ln -s /usr/bin/ld.gold /usr/bin/ld

script: make -j2 check
